Repository jhu-bids/TermHub, pull requests merged in 2023-06, with the labels that each got.

#333 DB Refresh Via Objects API
  .github/workflows/db_refresh.yml
  .github/workflows/refresh_db.yml
  backend/app.py
  backend/db/analysis.py
  backend/db/config.py
  backend/db/ddl-1-column_types.jinja.sql
  backend/db/ddl-10-cset_members_items_plus.jinja.sql
  backend/db/ddl-11-concepts_with_counts_ungrouped.jinja.sql
  backend/db/ddl-12-concepts_with_counts.jinja.sql
  backend/db/ddl-13-concept_relationship_plus.jinja.sql
  backend/db/ddl-2-primary_keys.jinja.sql
  backend/db/ddl-3-concept_set_members.jinja.sql
  backend/db/ddl-4-indexes.jinja.sql
  backend/db/ddl-5-concept_set_container.jinja.sql
  backend/db/ddl-6-cset_members_items.jinja.sql
  backend/db/ddl-7-members_items_summary.jinja.sql
  backend/db/ddl-8-codeset_counts.jinja.sql
  backend/db/ddl-9-all_csets.jinja.sql
  backend/db/ddl.jinja.sql
  backend/db/ddl_deprecated_statements.jinja.sql
  backend/db/initialize.py
  backend/db/load.py
  backend/db/refresh.py
  backend/db/reset_and_update.py
  backend/db/utils.py
  db_backup.sh
  docs/backend/db/analysis.md
  enclave_wrangler/models.py
  enclave_wrangler/objects_api.py
  enclave_wrangler/utils.py
  test/input/test_enclave_wrangler/test_csets_and_members_enclave_to_db/objects.pkl
  test/test_backend.py
  test/test_enclave_wrangler.py
Labels: new feature

#425 Initialize bugfixes
  backend/db/ddl-1-column_types.jinja.sql
  backend/db/ddl-14-concepts_with_counts_ungrouped.jinja.sql
  backend/db/ddl-15-concepts_with_counts.jinja.sql
  backend/db/ddl-16-concept_relationship_plus.jinja.sql
  backend/db/ddl_deprecated_statements.jinja.sql
  backend/db/initialize.py
  backend/db/load.py
  backend/db/reset_and_update.py
  backend/db/utils.py
  docs/backend/db/analysis.md
Labels: bug

#427 Filtering 0-member code sets
  backend/db/analysis.py
  backend/db/initialize.py
  backend/db/load.py
  backend/db/refresh.py
  backend/db/reset_and_update.py
  backend/db/utils.py
  enclave_wrangler/objects_api.py
  frontend/src/pages/AboutPage.js
  test/test_enclave_wrangler.py
Labels: bug, ux issue

#434 DDL updates / fixes
  backend/db/ddl-11-all_csets.jinja.sql
  backend/db/load.py
Labels: bug

#453 DB Refresh: Syntax error bugfix && other bugfixes
  backend/db/refresh.py
  backend/db/utils.py
  enclave_wrangler/objects_api.py
  enclave_wrangler/utils.py
Labels: bug

#389 PR: Test subgraph function and endpoint
  test/test_backend.py
Labels: qa / test

#462 Bugfix: DB refresh index error
  .github/workflows/refresh_db.yml
  backend/db/ddl-10-codeset_counts.jinja.sql
  backend/db/ddl-11-all_csets.jinja.sql
  backend/db/ddl-12-csets_to_ignore.jinja.sql
  backend/db/ddl-13-cset_members_items_plus.jinja.sql
  backend/db/ddl-14-concept_relationship_plus.jinja.sql
  backend/db/ddl-14-concepts_with_counts_ungrouped.jinja.sql
  backend/db/ddl-15-concepts_with_counts.jinja.sql
  backend/db/ddl-16-concept_relationship_plus.jinja.sql
  backend/db/ddl-4-indexes.jinja.sql
  backend/db/ddl-6-cset_members_items.jinja.sql
  backend/db/ddl-7-concept_ids_by_codeset_id.jinja.sql
  backend/db/ddl-8-codeset_ids_by_concept_id.jinja.sql
  backend/db/ddl-9-members_items_summary.jinja.sql
  backend/db/ddl_deprecated_statements.jinja.sql
  backend/db/refresh.py
  backend/db/utils.py
  enclave_wrangler/objects_api.py
Labels: bug
