Repository jhu-bids/TermHub, pull requests merged in 2024-11, with the labels that each got.

#934 Caching: Bunch of LRU, etc from claude.ai
  frontend/src/components/AddConcepts.tsx
  frontend/src/state/DataCache.jsx
  frontend/src/state/DataCacheLRU.jsx
  frontend/src/state/DataGetter.jsx
Labels: ux issue, performance

#976 Bug fix: DB refresh table order - redux
  backend/db/utils.py
  enclave_wrangler/config.py
Labels: bug

#883 Vocab refresh: Update `networkx` graphs
  .github/workflows/test_backend_e2e_and_unit_and_qc.yml
  backend/db/utils.py
  backend/routes/graph.py
  test/attic/testing_get_missing_in_between_nodes.py
  test/test_backend/routes/test_graph.py
  testing_get_missing_in_between_nodes.py
Labels: bug

#980 Security: Stop printing auth token
  enclave_wrangler/utils.py
Labels: bug, security

#914 Refactoring `displayRows` stuff, WIP - Joe comments & misc
  frontend/src/state/AppState.jsx
  frontend/src/state/GraphState.jsx
Labels: update

#984 Bug fix: Playwright tests
  .github/workflows/test_frontend_e2e_live_dev_running_local.yml
  .gitignore
  frontend/tests/playwright/basic-functions.test.js
  frontend/tests/playwright/large-cset-handling.test.js
Labels: bug, qa / test

#987 Sync Draft Expression Items
  backend/db/resolve_fetch_failures_0_members.py
  backend/db/utils.py
  enclave_wrangler/models.py
  enclave_wrangler/objects_api.py
Labels: bug
